figure()
subplot(3,2,1)
histogram(det_comp.imprint.Perc_z, BinWidth=0.2)
xlim([-3, 7])
xline(0)
title("Imprint Perc CLO captured (z)")
subplot(3,2,2)
histogram(det_comp.imprint.Jaccard_z, BinWidth=0.2)
xlim([-3, 7])
xline(0)
title("Imprint Jaccard (z)")


subplot(3,2,3)
histogram(det_comp.EI.Perc_z, BinWidth=0.2)
xlim([-3, 7])
xline(0)
title("EI Perc CLO captured (z)")
subplot(3,2,4)
histogram(det_comp.EI.Jaccard_z, BinWidth=0.2)
xlim([-3, 7])
xline(0)
title("EI Jaccard (z)")

subplot(3,2,5)
histogram(det_comp.PLHG.Perc_z, BinWidth=0.2)
xlim([-3, 7])
xline(0)
title("PLHG Perc CLO captured (z)")
subplot(3,2,6)
histogram(det_comp.PLHG.Jaccard_z, BinWidth=0.2)
xlim([-3, 7])
xline(0)
title("PLHG Jaccard (z)")

%%
figure()
subplot(221)
histogram(det_comp.imprint.Perc_z - det_comp.EI.Perc_z, BinWidth=0.2)
xline(0, 'r')
ylim([0 10])
xlim([-6 6])
title("Imprint perc z - EI perc z")
subplot(222)
histogram(det_comp.imprint.Perc_z - det_comp.PLHG.Perc_z, BinWidth=0.2)
xline(0, 'r')
ylim([0 10])
xlim([-6 6])
title("Imprint perc z - PLHG perc z")
subplot(223)
histogram(det_comp.imprint.Jaccard_z - det_comp.EI.Jaccard_z, BinWidth=0.2)
xline(0, 'r')
ylim([0 10])
xlim([-6 6])
title("Imprint Jaccard z - EI Jaccard z")
subplot(224)
histogram(det_comp.imprint.Jaccard_z - det_comp.PLHG.Jaccard_z, BinWidth=0.2)
xline(0, 'r')
ylim([0 10])
xlim([-6 6])
title("Imprint Jaccard z - PLHG Jaccard z")
%%
sum(det_comp.imprint.Perc_z > det_comp.EI.Perc_z)
sum(det_comp.imprint.Perc_z > det_comp.PLHG.Perc_z)

    sum(det_comp.imprint.Jaccard_z > det_comp.EI.Jaccard_z)
sum(det_comp.imprint.Jaccard_z > det_comp.PLHG.Jaccard_z)

%%
figure()
subplot(231)
scatter(grpstats(det_comp.imprint.Perc_z, det_comp.imprint.Patient_id, 'max'),...
    grpstats(det_comp.EI.Perc_z, det_comp.EI.Patient_id, 'max'))
xlabel("Imprint % CLO z")
ylabel("EI % CLO z")
lsline()
subplot(232)
scatter(grpstats(det_comp.imprint.Perc_z, det_comp.imprint.Patient_id, 'max'),...
    grpstats(det_comp.PLHG.Perc_z, det_comp.PLHG.Patient_id, 'max'))
xlabel("Imprint % CLO z")
ylabel("PLHG % CLO z")
lsline()
subplot(233)
scatter(grpstats(det_comp.EI.Perc_z, det_comp.EI.Patient_id, 'max'),...
    grpstats(det_comp.PLHG.Perc_z, det_comp.PLHG.Patient_id, 'max'))
lsline()
xlabel("EI % CLO z")
ylabel("PLHG % CLO z")

subplot(234)
scatter(grpstats(det_comp.imprint.Jaccard_z, det_comp.imprint.Patient_id, 'max'),...
    grpstats(det_comp.EI.Jaccard_z, det_comp.EI.Patient_id, 'max'))
lsline()
xlabel("Imprint Jaccard z")
ylabel("EI Jaccard z")
subplot(235)
scatter(grpstats(det_comp.imprint.Jaccard_z, det_comp.imprint.Patient_id, 'max'),...
    grpstats(det_comp.PLHG.Jaccard_z, det_comp.PLHG.Patient_id, 'max'))
lsline()
xlabel("Imprint Jaccard z")
ylabel("PLHG Jaccard z")
subplot(236)
scatter(grpstats(det_comp.EI.Jaccard_z, det_comp.EI.Patient_id, 'max'),...
    grpstats(det_comp.PLHG.Jaccard_z, det_comp.PLHG.Patient_id, 'max'))
lsline()
xlabel("EI Jaccard z")
ylabel("PLHG Jaccard z")
sgtitle("Comparing maximum value across seizures per individual")
