function plotBrain_png(regions, values, cm)
    roi_names = {...
        'Left-Thalamus-Proper'        ,...
        'Left-Caudate'                ,...
        'Left-Putamen'                ,...
        'Left-Pallidum'               ,...
        'Left-Hippocampus'            ,...
        'Left-Amygdala'               ,...
        'Left-Accumbens-area'         ,...
        'Right-Thalamus-Proper'       ,...
        'Right-Caudate'               ,...
        'Right-Putamen'               ,...
        'Right-Pallidum'              ,...
        'Right-Hippocampus'           ,...
        'Right-Amygdala'              ,...
        'Right-Accumbens-area'        ,...
        'l.bankssts_1'                ,...
        'l.caudalanteriorcingulate_1' ,...
        'l.caudalmiddlefrontal_1'     ,...
        'l.cuneus_1'                  ,...
        'l.entorhinal_1'              ,...
        'l.fusiform_1'                ,...
        'l.inferiorparietal_1'        ,...
        'l.inferiortemporal_1'        ,...
        'l.isthmuscingulate_1'        ,...
        'l.lateraloccipital_1'        ,...
        'l.lateralorbitofrontal_1'    ,...
        'l.lingual_1'                 ,...
        'l.medialorbitofrontal_1'     ,...
        'l.middletemporal_1'          ,...
        'l.parahippocampal_1'         ,...
        'l.paracentral_1'             ,...
        'l.parsopercularis_1'         ,...
        'l.parsorbitalis_1'           ,...
        'l.parstriangularis_1'        ,...
        'l.pericalcarine_1'           ,...
        'l.postcentral_1'             ,...
        'l.posteriorcingulate_1'      ,...
        'l.precentral_1'              ,...
        'l.precuneus_1'               ,...
        'l.rostralanteriorcingulate_1',...
        'l.rostralmiddlefrontal_1'    ,...
        'l.superiorfrontal_1'         ,...
        'l.superiorparietal_1'        ,...
        'l.superiortemporal_1'        ,...
        'l.supramarginal_1'           ,...
        'l.frontalpole_1'             ,...
        'l.temporalpole_1'            ,...
        'l.transversetemporal_1'      ,...
        'l.insula_1'                  ,...
        'l.fusiform_2'                ,...
        'l.inferiorparietal_2'        ,...
        'l.inferiortemporal_2'        ,...
        'l.lateraloccipital_2'        ,...
        'l.lateralorbitofrontal_2'    ,...
        'l.lingual_2'                 ,...
        'l.middletemporal_2'          ,...
        'l.postcentral_2'             ,...
        'l.postcentral_3'             ,...
        'l.precentral_2'              ,...
        'l.precentral_3'              ,...
        'l.precentral_4'              ,...
        'l.precuneus_2'               ,...
        'l.rostralmiddlefrontal_2'    ,...
        'l.rostralmiddlefrontal_3'    ,...
        'l.superiorfrontal_2'         ,...
        'l.superiorfrontal_3'         ,...
        'l.superiorfrontal_4'         ,...
        'l.superiorparietal_2'        ,...
        'l.superiorparietal_3'        ,...
        'l.superiortemporal_2'        ,...
        'l.supramarginal_2'           ,...
        'l.insula_2'                  ,...
        'r.bankssts_1'                ,...
        'r.caudalanteriorcingulate_1' ,...
        'r.caudalmiddlefrontal_1'     ,...
        'r.cuneus_1'                  ,...
        'r.entorhinal_1'              ,...
        'r.fusiform_1'                ,...
        'r.inferiorparietal_1'        ,...
        'r.inferiortemporal_1'        ,...
        'r.isthmuscingulate_1'        ,...
        'r.lateraloccipital_1'        ,...
        'r.lateralorbitofrontal_1'    ,...
        'r.lingual_1'                 ,...
        'r.medialorbitofrontal_1'     ,...
        'r.middletemporal_1'          ,...
        'r.parahippocampal_1'         ,...
        'r.paracentral_1'             ,...
        'r.parsopercularis_1'         ,...
        'r.parsorbitalis_1'           ,...
        'r.parstriangularis_1'        ,...
        'r.pericalcarine_1'           ,...
        'r.postcentral_1'             ,...
        'r.posteriorcingulate_1'      ,...
        'r.precentral_1'              ,...
        'r.precuneus_1'               ,...
        'r.rostralanteriorcingulate_1',...
        'r.rostralmiddlefrontal_1'    ,...
        'r.superiorfrontal_1'         ,...
        'r.superiorparietal_1'        ,...
        'r.superiortemporal_1'        ,...
        'r.supramarginal_1'           ,...
        'r.frontalpole_1'             ,...
        'r.temporalpole_1'            ,...
        'r.transversetemporal_1'      ,...
        'r.insula_1'                  ,...
        'r.fusiform_2'                ,...
        'r.inferiorparietal_2'        ,...
        'r.inferiorparietal_3'        ,...
        'r.inferiortemporal_2'        ,...
        'r.lateraloccipital_2'        ,...
        'r.lateraloccipital_3'        ,...
        'r.lateralorbitofrontal_2'    ,...
        'r.lingual_2'                 ,...
        'r.medialorbitofrontal_2'     ,...
        'r.middletemporal_2'          ,...
        'r.postcentral_2'             ,...
        'r.precentral_2'              ,...
        'r.precentral_3'              ,...
        'r.precuneus_2'               ,...
        'r.rostralmiddlefrontal_2'    ,...
        'r.superiorfrontal_2'         ,...
        'r.superiorfrontal_3'         ,...
        'r.superiorfrontal_4'         ,...
        'r.superiorparietal_2'        ,...
        'r.superiorparietal_3'        ,...
        'r.superiortemporal_2'        ,...
        'r.supramarginal_2'           ,...
        'r.insula_2'                  ,...
    };
    colormap(cm)
    cm = colormap;
    
    
    filename = 'plot_lausanne120_aseg_lowres.png';
    png = imread(filename);

    % matlab is less annoying this way round
    png_copy = permute(png,[3,1,2]);
    png_slice = png_copy(1,:,:);

    % set a colour for every region
    colours = ones(128,3)*255;
    for i = 1:length(regions)
        index = find(strcmp(regions{i},roi_names));
        if isempty(index)
            error(regions{i} + " is not a valid region name");
        end
        % force values to go from 1 to max for colourmap
        if max(values)-min(values) == 0
            colour = cm(1,:);
        else
            colour = cm(round(((values(i)-min(values))/(max(values)-min(values)))*(size(cm,1)-1))+1,:);
        end
        colours(index,:) = round(colour*255);
    end
    
    % set new colour for every region
    for i = 1:size(png,1)
        for j = 1:size(png,2)
            if (png_slice(1,i,j) > 0 && png_slice(1,i,j) < 129)
                png_copy(1,i,j) = colours(png_slice(1,i,j),1);
                png_copy(2,i,j) = colours(png_slice(1,i,j),2);
                png_copy(3,i,j) = colours(png_slice(1,i,j),3);
            end
        end
    end

    % switch back
    png = permute(png_copy,[2,3,1]);
    
    % plot
    imshow(png);
%     colormap(cm)
%     cbh = colorbar ; %Create Colorbar
%     cbh.Ticks = values; 
%     cbh.TickLabels = num2cell(values) ; 
%     clim([min(values), max(values)]);
end